package gitclaw

import (
	"context"
	"strings"
	"testing"
)

func TestHandleChannelCheckpointStatusQueuesReadinessCardWithoutLLM(t *testing.T) {
	root := t.TempDir()
	initCheckpointRiskRepo(t, root)

	threadBody := RenderChannelThreadBody(ChannelIngestOptions{
		Channel:  "telegram",
		ThreadID: "chat-checkpoint-status-123",
	})
	ev, err := ParseEvent("issue_comment", []byte(`{
		"action": "created",
		"repository": {"full_name": "owner/repo", "default_branch": "main"},
		"issue": {
			"number": 917,
			"title": "GitClaw telegram thread chat-checkpoint-status-123",
			"body": "<!-- gitclaw:channel-thread channel=\"telegram\" thread_id=\"chat-checkpoint-status-123\" -->\nGitClaw channel bridge thread.",
			"author_association": "MEMBER",
			"user": {"login": "alice", "type": "User"},
			"labels": [{"name": "gitclaw"}, {"name": "gitclaw:channel"}]
		},
		"comment": {
			"id": 91701,
			"body": "@gitclaw /channels checkpoint-status --message-id checkpoint-status-inbound-917 --notify-message-id checkpoint-status-notify-917 --status-id Checkpoint.Status.Secret.917\nDo not include this command hidden token in the receipt: CHANNEL_CHECKPOINT_STATUS_COMMAND_SECRET.",
			"author_association": "MEMBER",
			"user": {"login": "alice", "type": "User"}
		},
		"sender": {"login": "alice", "type": "User"}
	}`))
	if err != nil {
		t.Fatalf("ParseEvent returned error: %v", err)
	}
	cfg := DefaultConfig()
	cfg.Workdir = root
	github := &FakeGitHub{
		Issues: []Issue{{
			Number: 917,
			Title:  "GitClaw telegram thread chat-checkpoint-status-123",
			Body:   threadBody,
			Labels: []string{"gitclaw", "gitclaw:channel"},
		}},
		CommentsByIssue: map[int][]Comment{917: {{
			ID: 91700,
			Body: RenderChannelMessageComment(ChannelIngestOptions{
				Channel:   "telegram",
				ThreadID:  "chat-checkpoint-status-123",
				MessageID: "checkpoint-status-inbound-917",
				Author:    "telegram",
				Body:      "Original mirrored checkpoint status command with CHANNEL_CHECKPOINT_STATUS_INGEST_SECRET.",
			}),
		}}},
		IssueLabels: map[int][]string{917: []string{"gitclaw", "gitclaw:channel"}},
	}
	llm := &FakeLLM{Response: "should not be called"}

	if err := Handle(context.Background(), ev, cfg, github, llm); err != nil {
		t.Fatalf("Handle returned error: %v", err)
	}
	if llm.Calls != 0 {
		t.Fatalf("LLM called %d times for channel checkpoint status action", llm.Calls)
	}
	if len(github.Issues) != 1 {
		t.Fatalf("checkpoint status action should not create issues: %#v", github.Issues)
	}
	sourceComments := github.CommentsByIssue[917]
	if len(sourceComments) != 3 {
		t.Fatalf("source comments = %d, want message + outbound + receipt: %#v", len(sourceComments), sourceComments)
	}

	outbound := sourceComments[1].Body
	for _, want := range []string{
		"gitclaw:channel-outbound",
		`channel="telegram"`,
		`message_id="checkpoint-status-notify-917"`,
		"GitClaw channel checkpoint status",
		"Checkpoint status: clean",
		"Checkpoint risk status: ok",
		"Checkpoint strategy: git-history-plus-backup-branch",
		"Rollback mode: inspect-only",
		"Git available: true",
		"Git repository: true",
		"Worktree root: .",
		"Branch: main",
		"Head commit: ",
		"Commits available: 1",
		"Recent commits returned: 1",
		"Worktree clean: true",
		"Staged changes: 0",
		"Unstaged changes: 0",
		"Untracked files: 0",
		"Backup branch: gitclaw-backups",
		"Backup branch local ref: false",
		"Risk findings: 0",
		"High risk findings: 0",
		"Warning risk findings: 0",
		"Info risk findings: 0",
		"Status id hash: ",
		"Recent commits:",
		"subject_sha256_12=",
		"raw_subject_included=false",
		"raw_diff_included=false",
		"Risk findings:",
		"- none",
		"Safe follow-up commands:",
		"gitclaw checkpoints status",
		"gitclaw checkpoints preview HEAD~1",
		"gitclaw checkpoints risk",
		"gitclaw rollback diff HEAD~1",
		"@gitclaw /channels rehearse-checkpoint --target HEAD~1 --message-id <id>",
		"Raw diffs: not generated by this action.",
		"Raw file bodies: not included.",
		"Raw commit subjects: not included.",
		"Restore: not performed by this action.",
		"Git reset: not performed by this action.",
		"Git clean: not performed by this action.",
		"Checkout mutation: not performed by this action.",
		"Model call: not performed by this action.",
		"Repository mutation: not performed by this action.",
		"Provider delivery: queued through GitHub channel outbox.",
	} {
		if !strings.Contains(outbound, want) {
			t.Fatalf("checkpoint status notification missing %q:\n%s", want, outbound)
		}
	}
	for _, leaked := range []string{"CHANNEL_CHECKPOINT_STATUS_COMMAND_SECRET", "CHANNEL_CHECKPOINT_STATUS_INGEST_SECRET", "CHECKPOINT_COMMIT_SECRET", "CHECKPOINT_FILE_SECRET", "Checkpoint.Status.Secret.917"} {
		if strings.Contains(outbound, leaked) {
			t.Fatalf("checkpoint status notification leaked %q:\n%s", leaked, outbound)
		}
	}

	receipt := sourceComments[2].Body
	for _, want := range []string{
		"GitClaw Channel Checkpoint Status Action",
		"Generated without a model call",
		`model="gitclaw/channels"`,
		"requested_channel_command: `/channels checkpoint-status`",
		"channel_checkpoint_status_status: `queued`",
		"checkpoint_snapshot_mode: `provider-facing-rollback-readiness`",
		"checkpoint_status: `clean`",
		"checkpoint_risk_status: `ok`",
		"checkpoint_strategy: `git-history-plus-backup-branch`",
		"rollback_mode: `inspect-only`",
		"notification_target_issue: `#917`",
		"notification_comment_id: `9000`",
		"notification_queued: `true`",
		"notification_duplicate_suppressed: `false`",
		"target_from_current_channel_issue: `true`",
		"checkpoint_status_id_sha256_12: `",
		"checkpoint_status_id_auto: `false`",
		"git_available: `true`",
		"git_repository: `true`",
		"worktree_root: `.`",
		"branch: `main`",
		"head_commit: `",
		"commits_available: `1`",
		"recent_commits_returned: `1`",
		"recent_commit_limit: `5`",
		"recent_commit_index_sha256_12: `",
		"worktree_clean: `true`",
		"staged_changes: `0`",
		"unstaged_changes: `0`",
		"untracked_files: `0`",
		"backup_branch: `gitclaw-backups`",
		"backup_branch_local_ref: `false`",
		"surfaces_with_risk_findings: `0`",
		"checkpoint_risk_findings: `0`",
		"high_risk_findings: `0`",
		"warning_risk_findings: `0`",
		"info_risk_findings: `0`",
		"risk_finding_index_sha256_12: `none`",
		"raw_diffs_included: `false`",
		"raw_file_bodies_included: `false`",
		"restore_operations_enabled: `false`",
		"git_reset_allowed: `false`",
		"git_clean_allowed: `false`",
		"checkout_mutation_allowed: `false`",
		"pre_restore_snapshot_required: `true`",
		"rollback_diff_preview_required: `true`",
		"backup_manifest_required_for_restore: `true`",
		"shadow_store_path_included: `false`",
		"notification_body_sha256_12: `",
		"notification_body_bytes: `",
		"notification_body_lines: `",
		"model_call_performed: `false`",
		"repository_mutation_performed: `false`",
		"restore_performed: `false`",
		"git_reset_performed: `false`",
		"git_clean_performed: `false`",
		"checkout_mutation_performed: `false`",
		"raw_diff_generation_performed: `false`",
		"provider_delivery_performed: `false`",
		"provider_delivery_strategy: `channel-outbox + channel-delivery`",
		"raw_thread_id_included: `false`",
		"raw_source_message_id_included: `false`",
		"raw_notify_message_id_included: `false`",
		"raw_checkpoint_status_id_included: `false`",
		"raw_channel_message_body_included: `false`",
		"raw_issue_bodies_included: `false`",
		"raw_comment_bodies_included: `false`",
		"raw_commit_subjects_included: `false`",
		"raw_diffs_included_in_notification: `false`",
		"raw_file_bodies_included_in_notification: `false`",
		"raw_prompts_included: `false`",
		"raw_tool_outputs_included: `false`",
		"credential_values_included: `false`",
		"llm_e2e_required_after_channel_checkpoint_status_change: `true`",
	} {
		if !strings.Contains(receipt, want) {
			t.Fatalf("checkpoint status receipt missing %q:\n%s", want, receipt)
		}
	}
	for _, leaked := range []string{"CHANNEL_CHECKPOINT_STATUS_COMMAND_SECRET", "CHANNEL_CHECKPOINT_STATUS_INGEST_SECRET", "CHECKPOINT_COMMIT_SECRET", "CHECKPOINT_FILE_SECRET", "chat-checkpoint-status-123", "checkpoint-status-inbound-917", "checkpoint-status-notify-917", "Checkpoint.Status.Secret.917"} {
		if strings.Contains(receipt, leaked) {
			t.Fatalf("checkpoint status receipt leaked %q:\n%s", leaked, receipt)
		}
	}

	duplicateEv, err := ParseEvent("issue_comment", []byte(`{
		"action": "created",
		"repository": {"full_name": "owner/repo", "default_branch": "main"},
		"issue": {
			"number": 917,
			"title": "GitClaw telegram thread chat-checkpoint-status-123",
			"body": "<!-- gitclaw:channel-thread channel=\"telegram\" thread_id=\"chat-checkpoint-status-123\" -->\nGitClaw channel bridge thread.",
			"author_association": "MEMBER",
			"user": {"login": "alice", "type": "User"},
			"labels": [{"name": "gitclaw"}, {"name": "gitclaw:channel"}]
		},
		"comment": {
			"id": 91702,
			"body": "@gitclaw /channels rollback-status --message-id checkpoint-status-inbound-917 --notify-message-id checkpoint-status-notify-917 --status-id Checkpoint.Status.Secret.917\nDo not leak duplicate token CHANNEL_CHECKPOINT_STATUS_DUPLICATE_SECRET.",
			"author_association": "MEMBER",
			"user": {"login": "alice", "type": "User"}
		},
		"sender": {"login": "alice", "type": "User"}
	}`))
	if err != nil {
		t.Fatalf("ParseEvent duplicate returned error: %v", err)
	}
	if err := Handle(context.Background(), duplicateEv, cfg, github, llm); err != nil {
		t.Fatalf("Handle duplicate returned error: %v", err)
	}
	if got := len(github.CommentsByIssue[917]); got != 4 {
		t.Fatalf("duplicate checkpoint status posted another outbound comment: comments=%d %#v", got, github.CommentsByIssue[917])
	}
	duplicateReceipt := github.CommentsByIssue[917][3].Body
	for _, want := range []string{
		"GitClaw Channel Checkpoint Status Action",
		"requested_channel_command: `/channels rollback-status`",
		"channel_checkpoint_status_status: `duplicate`",
		"notification_queued: `false`",
		"notification_duplicate_suppressed: `true`",
		"model_call_performed: `false`",
		"repository_mutation_performed: `false`",
		"restore_performed: `false`",
	} {
		if !strings.Contains(duplicateReceipt, want) {
			t.Fatalf("duplicate checkpoint status receipt missing %q:\n%s", want, duplicateReceipt)
		}
	}
	for _, leaked := range []string{"CHANNEL_CHECKPOINT_STATUS_DUPLICATE_SECRET", "chat-checkpoint-status-123", "checkpoint-status-inbound-917", "checkpoint-status-notify-917", "Checkpoint.Status.Secret.917"} {
		if strings.Contains(duplicateReceipt, leaked) {
			t.Fatalf("duplicate checkpoint status receipt leaked %q:\n%s", leaked, duplicateReceipt)
		}
	}
}

func TestBuildChannelCheckpointStatusActionRequestParsesRouteAlias(t *testing.T) {
	root := t.TempDir()
	initCheckpointRiskRepo(t, root)
	cfg := DefaultConfig()
	cfg.Workdir = root
	ev := Event{
		Kind:      EventIssueComment,
		EventName: "issue_comment",
		Repo:      "owner/repo",
		Issue:     Issue{Number: 42, Title: "Channel checkpoint status"},
		Comment: &Comment{
			ID:   4201,
			Body: `@gitclaw /channel rollback-health --route team-demo --message-id source-1 --notify-message-id notify-1 --id Checkpoint.Status.One`,
		},
	}
	req, err := BuildChannelCheckpointStatusActionRequest(ev, cfg)
	if err != nil {
		t.Fatalf("BuildChannelCheckpointStatusActionRequest returned error: %v", err)
	}
	if req.Command != "/channel" || req.Subcommand != "rollback-health" || req.Options.Route != "team-demo" || req.Options.SourceMessageID != "source-1" || req.Options.NotifyMessageID != "notify-1" || req.Options.StatusID != "checkpoint-status-one" {
		t.Fatalf("unexpected channel checkpoint status parsing: %#v", req)
	}
	if req.TargetFromIssue || req.AutoNotifyMessageID || req.AutoSourceMessageID || req.AutoStatusID {
		t.Fatalf("unexpected channel checkpoint status defaults: %#v", req)
	}
	if req.RequestedRouteHash == "" || req.StatusIDHash == "" || req.NotificationBodySHA == "" || req.RecentCommitIndexSHA == "" || req.RiskFindingIndexSHA != "none" || req.Checkpoint.Status != "clean" || req.Risk.Status != "ok" {
		t.Fatalf("expected route checkpoint hashes and clean status: %#v", req)
	}
	if !IsChannelCheckpointStatusActionRequest(ev, cfg) {
		t.Fatalf("expected channel rollback-health alias to be recognized")
	}
}
