package gitclaw

import (
	"strings"
	"testing"
)

func TestRenderCommandReportListsCatalogWithoutBodies(t *testing.T) {
	ev, err := ParseEvent("issues", []byte(`{
		"action": "opened",
		"repository": {"full_name": "owner/repo", "default_branch": "main"},
		"issue": {
			"number": 109,
			"title": "@gitclaw /help",
			"body": "Hidden command body token: COMMAND_BODY_SECRET.",
			"author_association": "MEMBER",
			"user": {"login": "alice", "type": "User"},
			"labels": [{"name": "gitclaw"}]
		},
		"sender": {"login": "alice", "type": "User"}
	}`))
	if err != nil {
		t.Fatalf("ParseEvent returned error: %v", err)
	}
	report := RenderCommandReport(ev, DefaultConfig())
	for _, want := range []string{
		"GitClaw Commands Report",
		"Generated without a model call",
		"commands: `33`",
		"aliases: `31`",
		"local_cli_helpers: `115`",
		"run_mode: `read-only`",
		"### Slash Commands",
		"### Local CLI Helpers",
		"`/agents` model=`gitclaw/agents`",
		"aliases=`/agent`",
		"`/approvals` model=`gitclaw/approvals`",
		"aliases=`/approval`",
		"`/artifacts` model=`gitclaw/artifacts`",
		"aliases=`/artifact`",
		"`/diffs` model=`gitclaw/diffs`", "aliases=`/diff, /changes`", "`/help` model=`gitclaw/commands`",
		"aliases=`/commands`",
		"`/backup` model=`gitclaw/backup`",
		"`/bundles` model=`gitclaw/skills`",
		"`/checkpoints` model=`gitclaw/checkpoints`",
		"aliases=`/checkpoint, /rollback`",
		"`/heartbeat` model=`gitclaw/heartbeat`",
		"`/hooks` model=`gitclaw/hooks`",
		"aliases=`/hook`",
		"`/migrate` model=`gitclaw/migration`",
		"aliases=`/migration`",
		"`/nodes` model=`gitclaw/nodes`",
		"aliases=`/node`",
		"`/orders` model=`gitclaw/orders`",
		"aliases=`/standing-orders`",
		"`/plugins` model=`gitclaw/plugins`",
		"aliases=`/plugin`",
		"`/tools` model=`gitclaw/tools`",
		"`/workspace` model=`gitclaw/workspace`",
		"aliases=`/workdir, /repo`",
		"`/prompt` model=`gitclaw/prompt`",
		"aliases=`/budget, /prompt-budget`",
		"`/profile` model=`gitclaw/profile`",
		"aliases=`/profiles`",
		"`/tasks` model=`gitclaw/tasks`",
		"aliases=`/task`",
		"`/proactive` model=`gitclaw/proactive`",
		"aliases=`/cron`",
		"`/runs` model=`gitclaw/runs`",
		"aliases=`/run, /ledger`",
		"`/sandbox` model=`gitclaw/sandbox`",
		"aliases=`/sandboxes, /exec-policy`",
		"`/secrets` model=`gitclaw/secrets`",
		"aliases=`/secret`",
		"`gitclaw agents list` command=`/agents`",
		"`gitclaw agents risk` command=`/agents`",
		"`gitclaw agents verify` command=`/agents`",
		"`gitclaw approvals list` command=`/approvals`",
		"`gitclaw approvals verify` command=`/approvals`",
		"`gitclaw artifacts list` command=`/artifacts`",
		"`gitclaw artifacts risk` command=`/artifacts`",
		"`gitclaw artifacts verify` command=`/artifacts`",
		"`gitclaw channels verify` command=`/channels`",
		"`gitclaw channels risk` command=`/channels`",
		"`gitclaw bundles list` command=`/bundles`",
		"`gitclaw bundles info <name>` command=`/bundles`",
		"`gitclaw channels list` command=`/channels`",
		"`gitclaw channels info <provider>` command=`/channels`",
		"`gitclaw channel-state` command=`/channels`", "`gitclaw channel-gateway` command=`/channels`", "`gitclaw channel-delivery` command=`/channels`",
		"`gitclaw checkpoints status` command=`/checkpoints`",
		"`gitclaw checkpoints list` command=`/checkpoints`",
		"`gitclaw checkpoints risk` command=`/checkpoints`",
		"`gitclaw checkpoints verify` command=`/checkpoints`",
		"`gitclaw rollback list` command=`/checkpoints`",
		"`gitclaw rollback risk` command=`/checkpoints`",
		"`gitclaw config list` command=`/config`",
		"`gitclaw context list` command=`/context`",
		"`gitclaw context info <path>` command=`/context`", "`gitclaw diffs summary` command=`/diffs`", "`gitclaw diffs risk` command=`/diffs`", "`gitclaw diffs verify` command=`/diffs`",
		"`gitclaw doctor` command=`/doctor`",
		"`gitclaw doctor list` command=`/doctor`",
		"`gitclaw heartbeat status` command=`/heartbeat`",
		"`gitclaw hooks list` command=`/hooks`",
		"`gitclaw hooks risk` command=`/hooks`",
		"`gitclaw hooks verify` command=`/hooks`",
		"`gitclaw plugins list` command=`/plugins`",
		"`gitclaw plugins risk` command=`/plugins`",
		"`gitclaw plugins verify` command=`/plugins`",
		"`gitclaw prompt list` command=`/prompt`",
		"`gitclaw profile show` command=`/profile`",
		"`gitclaw profile verify` command=`/profile`",
		"`gitclaw profile risk` command=`/profile`",
		"`gitclaw tasks list` command=`/tasks`",
		"`gitclaw tasks risk` command=`/tasks`",
		"`gitclaw tasks verify` command=`/tasks`",
		"`gitclaw proactive list` command=`/proactive`",
		"`gitclaw proactive risk` command=`/proactive`",
		"`gitclaw proactive info <name>` command=`/proactive`",
		"`gitclaw runs current` command=`/runs`",
		"`gitclaw runs verify` command=`/runs`",
		"`gitclaw sandbox explain` command=`/sandbox`",
		"`gitclaw sandbox verify` command=`/sandbox`",
		"`gitclaw session list --backup <issue.json>` command=`/session`",
		"`gitclaw session risk --backup <issue.json>` command=`/session`",
		"`gitclaw session search <query> --backup <issue.json>` command=`/session`",
		"`gitclaw models list` command=`/models`", "`gitclaw models risk` command=`/models`",
		"`gitclaw nodes list` command=`/nodes`",
		"`gitclaw nodes risk` command=`/nodes`",
		"`gitclaw nodes verify` command=`/nodes`",
		"`gitclaw orders list` command=`/orders`",
		"`gitclaw orders verify` command=`/orders`",
		"`gitclaw secrets audit` command=`/secrets`",
		"`gitclaw secrets scan` command=`/secrets`",
		"`gitclaw secrets list` command=`/secrets`",
		"`gitclaw policy list` command=`/policy`",
		"`gitclaw policy verify` command=`/policy`",
		"`gitclaw backup verify` command=`/backup`",
		"`gitclaw backup risk` command=`/backup`",
		"`gitclaw backup manifest` command=`/backup`",
		"`gitclaw backup list` command=`/backup`",
		"`gitclaw backup info --issue <number>` command=`/backup`",
		"`gitclaw backup stats` command=`/backup`",
		"`gitclaw backup search <query>` command=`/backup`",
		"`gitclaw backup export-jsonl` command=`/backup`",
		"`gitclaw backup restore-plan` command=`/backup`",
		"`gitclaw backup retention-plan` command=`/backup`",
		"`gitclaw memory verify` command=`/memory`",
		"`gitclaw memory risk` command=`/memory`",
		"`gitclaw memory validate` command=`/memory`",
		"`gitclaw memory list` command=`/memory`",
		"`gitclaw memory promote-plan [target]` command=`/memory`",
		"`gitclaw memory info <path>` command=`/memory`",
		"`gitclaw memory search <query>` command=`/memory`",
		"`gitclaw migrate plan <source>` command=`/migrate`",
		"`gitclaw soul verify` command=`/soul`",
		"`gitclaw soul risk` command=`/soul`",
		"`gitclaw soul validate` command=`/soul`",
		"`gitclaw soul list` command=`/soul`",
		"`gitclaw soul edit-plan <path>` command=`/soul`",
		"`gitclaw soul info <path>` command=`/soul`",
		"`gitclaw soul search <query>` command=`/soul`",
		"`gitclaw skills verify` command=`/skills`",
		"`gitclaw skills risk` command=`/skills`",
		"`gitclaw skills validate` command=`/skills`",
		"`gitclaw skills check` command=`/skills`",
		"`gitclaw skills list` command=`/skills`",
		"`gitclaw skills install-plan <target>` command=`/skills`",
		"`gitclaw skills upgrade-plan <target>` command=`/skills`",
		"`gitclaw skills info <name>` command=`/skills`",
		"`gitclaw skills search <query>` command=`/skills`",
		"`gitclaw tools verify` command=`/tools`",
		"`gitclaw tools risk` command=`/tools`",
		"`gitclaw tools validate` command=`/tools`",
		"`gitclaw tools list` command=`/tools`",
		"`gitclaw tools run-plan <name>` command=`/tools`",
		"`gitclaw tools info <name>` command=`/tools`",
		"`gitclaw tools search <query>` command=`/tools`",
		"`gitclaw workspace summary` command=`/workspace`",
		"`gitclaw workspace risk` command=`/workspace`",
		"`gitclaw workspace verify` command=`/workspace`",
	} {
		if !strings.Contains(report, want) {
			t.Fatalf("command report missing %q:\n%s", want, report)
		}
	}
	if strings.Contains(report, "COMMAND_BODY_SECRET") {
		t.Fatalf("command report leaked issue body token:\n%s", report)
	}
}

func TestIsCommandReportRequestAcceptsCommandsAlias(t *testing.T) {
	ev, err := ParseEvent("issues", []byte(`{
		"action": "opened",
		"repository": {"full_name": "owner/repo", "default_branch": "main"},
		"issue": {
			"number": 110,
			"title": "@gitclaw /commands",
			"body": "",
			"author_association": "MEMBER",
			"user": {"login": "alice", "type": "User"},
			"labels": [{"name": "gitclaw"}]
		},
		"sender": {"login": "alice", "type": "User"}
	}`))
	if err != nil {
		t.Fatalf("ParseEvent returned error: %v", err)
	}
	if !IsCommandReportRequest(ev, DefaultConfig()) {
		t.Fatalf("/commands should be accepted as command report alias")
	}
}
